"""Data models and schemas"""
from app.models.schemas import (
    DetectionResults,
    JobStatus,
    BoundingBox,
    DetectionObject,
    DetectionFrame,
    VideoMetadata,
    ModelMetadata,
    SpriteMetadata,
    DetectionStatistics,
    ProcessingMetadata,
    ResultsMetadata,
)
from app.models.result_models import (
    HealthResponse,
    AnalysisRequest,
    AnalysisResponse,
    JobStatusResponse,
    JobsListResponse,
    QueueStatusResponse,
    DetectionResultsModel,
    ErrorResponse,
    JobInfo,
    QueuedJob,
    CurrentJob,
    DeleteJobResponse,
    BoundingBoxModel,
    DetectionObjectModel,
    DetectionFrameModel,
    VideoMetadataModel,
    ModelMetadataModel,
    SpriteMetadataModel,
    DetectionStatisticsModel,
    ProcessingMetadataModel,
    ResultsMetadataModel,
    JobIdPath,
)

__all__ = [
    # From schemas
    "DetectionResults",
    "JobStatus",
    "BoundingBox",
    "DetectionObject",
    "DetectionFrame",
    "VideoMetadata",
    "ModelMetadata",
    "SpriteMetadata",
    "DetectionStatistics",
    "ProcessingMetadata",
    "ResultsMetadata",
    # From result_models
    "HealthResponse",
    "AnalysisRequest",
    "AnalysisResponse",
    "JobStatusResponse",
    "JobsListResponse",
    "QueueStatusResponse",
    "DetectionResultsModel",
    "ErrorResponse",
    "JobInfo",
    "QueuedJob",
    "CurrentJob",
    "DeleteJobResponse",
    "BoundingBoxModel",
    "DetectionObjectModel",
    "DetectionFrameModel",
    "VideoMetadataModel",
    "ModelMetadataModel",
    "SpriteMetadataModel",
    "DetectionStatisticsModel",
    "ProcessingMetadataModel",
    "ResultsMetadataModel",
    "JobIdPath",
]
