---
name: Release
on:
  push:
    branches: ["main"]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Running release-it 
        uses: juancarlosjr97/release-it-containerized@0.7.74
        with:
            github_token: ${{ secrets.PROJECT_GITHUB_TOKEN }}
            plugins_list: "@release-it/conventional-changelog,@release-it/bumper"
            git_username: github-actions[bot]
            git_email: github-actions[bot]@users.noreply.github.com